package entities;
// Generated May 4, 2019 1:53:27 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails implements java.io.Serializable {

	private int productid;
	private int ordersid;
	private int price;
	private int quantity;

	public Orderdetails() {
	}

	public Orderdetails(int productid, int ordersid, int price, int quantity) {
		this.productid = productid;
		this.ordersid = ordersid;
		this.price = price;
		this.quantity = quantity;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public int getOrdersid() {
		return this.ordersid;
	}

	public void setOrdersid(int ordersid) {
		this.ordersid = ordersid;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
