package entities;
// Generated May 4, 2019 1:53:27 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int id;
	private String name;
	private Date datecreation;
	private int status;
	private String username;

	public Orders() {
	}

	public Orders(int id, String name, Date datecreation, int status, String username) {
		this.id = id;
		this.name = name;
		this.datecreation = datecreation;
		this.status = status;
		this.username = username;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
